### PR TITLE
GAB_ADM0,1,2 gbOpen

### PR DESCRIPTION
**Pull request by rmbiddle**
Digitization of GAB_ADM0-2

## Why do we need this boundary?  
 #50

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
thank you for doing these so quickly! a few things need to be fixed and then they'll be good to go. 
1) one of your ADM2 features has "NULL" in the attribute table where it should say adm2, you need to edit that file so that one says ADM2 too
2) for ADM1 and 0, because you used a different file (from 2005) you need to update the year on your metadata to 2005 instead of 2017
3)  i'm pretty sure you don't need to include the image you digitized in your zipfile, but am checking with sydney and silvia so hold off on resubmitting these files until i confirm with them and let you know

**Review by lydiatroup — CHANGES_REQUESTED** [review]
just a couple things left to fix!
1) projection: when you digitize a boundary it defaults to use whatever projection your map was in, which is generally not the one we want. To fix this, you'll need to project your digitized shapefiles into the correct coordinate system ( EPSG 4326 ) 
2) your adm1 zipfile has another zipfile inside of it that you'll need to remove
3) there's still that null value for one of your ADM2's level field. To fix this you can either edit that specific field for that specific feature or you could make a new field for level and set them all to = adm2.  
let me know if you have any questions!

**Review by sgmurphy216 — APPROVED** [review]
Great work Russ- super granular digitization! Closes #50

**Review by lydiatroup — APPROVED** [review]

**Comment by DanRunfola** [comment]
Wow, wonderful detail on this.  Nice work.

**Pull request merged**
