### PR TITLE
NZL_ADM4 gbOpen

### PR DESCRIPTION
**Pull request by nmspage**
## Why do we need this boundary?  
 #824 

## Checklist:

- [x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by slfuhrig** [comment]
There is an issue with the topology of this boundary that needs to be addressed due to the presence of hundreds of small polygons for every lake in the country.

**Comment by larogersWM** [comment]
This layer is filled with lots (900+) little lakes and Inland Bays as individual polygons that need to be fixed. There are tiny lakes completely surrounded by a suburb/localities, larger lakes that span multiple localities, and inland bays that are even larger, which makes removing the lakes even more difficult. I'm wondering if there is a way to dissolve polygons completely surrounded by one other polygon. I left the attribute table as given, just in case.

**Comment by DanRunfola** [comment]
Thanks for posting this PR - this is a unique one, and really challenges our definition of "terrestrial".

A little background:
1) geoBoundaries focuses on land borders - i.e., we don't handle maritime boundaries.
2) However, we don't (as an example) remove rivers or streams from our data; more generally, landlocked lakes (well, or lakes that are fully surrounded by land within a single country) are retained, but we've never really made a firm decision on that.

In this case, we're faced with a few unique issues:
1) The lakes are individual polygons, so simply removing them would result in a huge number of holes in the data.
2) We don't know the appropriate way to dissolve lakes, so as to ascribe ownership to the appropriate polygon.
3) We can't leave the lakes, as our database only has administrative boundaries - i.e., each row is an adm boundary.

I'm leaning towards - for now - "remove all the lakes and leave the holes".  We then create an issue for ~gb 5.0 to go in and manually correct it by aggregating the lakes with the appropriate boundaries.  Recognizing it's a bit of a bummer to go that way, but I can't think of a better solution.

What do ya'll think?

**Comment by slfuhrig** [comment]
If we cannot find a suitable shapefile without lakes from another source, I agree that it's best to just remove them from this file for the 4.0 release and work to find another for 5.0 My concern is that the problem exists in ADM0-3 as well.

**Comment by larogersWM** [comment]
I just checked NZL_ADM 1, 2, and 3 and the lakes are not a problem there because the shapefile comes from a different source. I I have figured out how to manually select the lakes and fill them, which would help for the very tiny lakes that we know which suburb/locality they belong in (i.e. if the lake is completely surrounded by one suburb/locality). Then I can leave bigger holes for the large lakes and inland bays. This will be time consuming, so if it not the most important or will likely not result in the layer we want, I can simply remove the lakes and leave a lot of holes in the layer for 5.0 -- I am fine with either.

**Comment by DanRunfola** [comment]
I'm goign to go ahead and accept this one - our auto-gap-filling algorithms will catch very small lakes.  We'll want to revisit in the future for a more permanent solution.

**Comment by DanRunfola** [comment]
Oh, well, I'll accept after we fix: 
Detected Key / Value: Boundary Type / Suburbs and Localities
CRITICAL ERROR: The boundary type in the meta.txt file is invalid: Suburbs and Localities
We expect one of: ['ADM0', 'ADM1', 'ADM2', 'ADM3', 'ADM4', 'ADM5']

**Pull request closed without merging**
