### PR TITLE
SPM ADM0

### PR DESCRIPTION
**Pull request by leeberryman**
Thanks @alex-imb! 

 SPM ADM0
 This is digitized from Sentinel2 imagery.

## Why do we need this boundary?  
 #2961

### CODE REVIEW

**Comment by DanRunfola** [comment]
Thanks Lee!  Going to have our Data Engineer work on this - may have to redo the PR so it kicks off our bot (not quite sure why it didn't in this case, so going to check).

**Comment by rohith4444** [comment]
Hello @leeberryman,

No files have been altered in the commit. We're uncertain how this pull request was generated without any file modifications.

**Comment by leeberryman** [comment]
@rohith4444 I took a branch on @alex-imb's fork and pulled it into my branch on geoboundaries SPM ADM0 and created a pull request from this branch to main.  Can you see the additional files?

**Comment by DanRunfola** [comment]
@leeberryman looks like the files themselves aren't being included in some step here - i.e., the diff itself is "0", indicating that no changes are present from this commit vs. the gB main.  My guess is this has somethign to do with our use of LFS, and how that might interact with a fork that doesn't have LFS installed?

I added @alex-imb to the collaborators list, so I think they'll be able to commit direclty now.

**Comment by leeberryman** [comment]
Thanks @DanRunfola, @alex-imb will go ahead and make a new commit.

**Comment by jingjli1** [comment]
Looks good!

**Review by jingjli1 — APPROVED** [review]
looks good

**Pull request merged**
