### PR TITLE
IND_ADM3 gbOpen

### PR DESCRIPTION
**Pull request by maxmalynowsky**
## Why do we need this boundary?  

Fixed sliver gaps and geometry errors in previous submission.

### CODE REVIEW

**Review by lydiatroup — APPROVED** [review]
I will accept this file for now as it fixes geometry errors in our current file, but as an FYI going forwards we no longer use the "Open Data Commons Open Database License 1.0" license type for new submissions to our database. We are actually currently in the process of replacing all files with that license type with more open files.

**Comment by leeberryman** [comment]
@lydiatroup & @maxmalynowsky please note that the geonode.pathwaysdata.com server that hosts the source data has changed the license to CC BY 4.0

**Comment by lydiatroup** [comment]
@leeberryman, that is great to hear! Thank you for updating us, will be sure to update our files from that source.

**Review by lydiatroup — CHANGES_REQUESTED** [review]
please change license type to "Creative Commons Attribution 4.0 (CC BY 4.0)"

**Pull request closed without merging**
