### PR TITLE
#1141 gbOpen IND_ADM2

### PR DESCRIPTION
**Pull request by leeberryman**
#1141 Trying again with only IND_ADM2 changes.

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
Only two small changes are needed. We need you to change the license source field in your metadata to be the link to the webpage with the license information (the page you screenshotted for license.png). Also, we need you to delete the ISO field in your geoJson.

**Comment by leeberryman** [comment]
@lydiatroup done

**Review by lydiatroup — CHANGES_REQUESTED** [review]
it looks like you changed the "Source 2" field, not the "License Source" one. Please fix the license source field to what you currently have in source 2!

**Comment by leeberryman** [comment]
@lydiatroup done

**Review by lydiatroup — APPROVED** [review]
This one looks good too! Thank you again!

**Comment by DanRunfola** [comment]
Thank you for the submission - this should get incorporated during the next IND nightly.

**Pull request merged**
