### PR TITLE
ARM_ADM2

### PR DESCRIPTION
**Pull request by taraamcl**
70 new shapefile

## Checklist:

- [X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
You're pretty close, but a few things are off. First, the license screenshot and meta don't match up in some spots, so please double check everything and make edits where needed. Second, the shapefile is "empty" when I open it, so I'd recommend downloading and cleaning the data again. Make sure you open/extract the zipfile before you open the shapefile. Sometimes that can cause problems. Let me know if you need help with anything.

**Review by slfuhrig — APPROVED** [review]
Perfect!

**Comment by DanRunfola** [comment]
Can you guys do a quick resubmission on this one, if needed? It looks like I accepted another ARM ADM2 before this one, and I'm not sure if this is still necessary or not.

**Comment by taraamcl** [comment]
The first submission did not have meta.txt and for some reason the bot
didn't flag it. I will resubmit it now.

**Pull request closed without merging**
