### PR TITLE
PNG_ADM3 gbOpen

### PR DESCRIPTION
**Pull request by rmbiddle**
## Why do we need this boundary?  
 #1492

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey! Your file looks great but the bot is super picky about exact matching on the meta.txt. Try copying the appropriate license from https://github.com/wmgeolab/geoBoundaryBot/blob/main/dta/gbLicenses.csv  and pasting it into the License Type field when you resubmit- then we should be good.

**Comment by sgmurphy216** [comment]
Looks like license name is missing a closing bracket

**Comment by rmbiddle** [comment]
Hey Sean, I’ve tried submitting PNG_ADM3 a few times, the first two times the license was directly copied and pasted from the license csv and still failed so if it fails this time I’m not entirely sure what the issue is. Also, I was wondering if you saw my slack message about MMR issue. Sent from Mail for Windows 10 From: Sean MurphySent: Thursday, June 24, 2021 1:19 PMTo: wmgeolab/geoBoundariesCc: rmbiddle; AuthorSubject: Re: [wmgeolab/geoBoundaries] PNG_ADM3 gbOpen (#1495) Looks like license name is missing a closing bracket—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Review by sgmurphy216 — APPROVED** [review]

**Comment by sgmurphy216** [comment]
Perfect- license field fixed. I did see your MMR message- going to make an issue on that shortly! Thank you! Closes #1492

**Pull request merged**
