### PR TITLE
BRA_ADM1 #2670

### PR DESCRIPTION
**Pull request by jamesnelmore**
- #2670 BRA_ADM1
- fixed meta

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
A few changes needed for this file:
1) the name of the shapefile itself should be titled BRA_ADM1
2) source 2 in the meta data should be "Wikimedia Commons" because that is where the digitized image came from

also a note for the future, the automated digitizing is definitely cool, but you will need to smooth out the edges for file submissions from it (ie making them not as jagged / pixelated on the feature's edges)

**Review by lydiatroup — CHANGES_REQUESTED** [review]
A few changes are needed:
- Source 1: should be geoBoundaries and source2: should be Wikimedia Commons
- Your attribute table has a few extra columns. Please remove the InPoly_FID, Shape_Le_1, and Shape_Area fields
- In the attribute table your ISO_Code and Level columns are flipped. ISO_Code should be the BR- values, while Level should be "ADM1"

Also great work on smoothing out the lines! this looks really good.

**Comment by jamesnelmore** [comment]
I've made those changes. Thank you!

**Review by lydiatroup — APPROVED** [review]
looks great!! thanks! closes #2670

**Pull request merged**
