### PR TITLE
#2008 gB Administrative LSO 0-2

### PR DESCRIPTION
**Pull request by SidonieH**
## Why do we need this boundary?  
 #2008

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey! This looks good- could you add ISO_Code to LSO_ADM1 and resubmit? Thank you!

**Comment by SidonieH** [comment]
On further inspection of LSO ADM 1 - there appear to be doubled districts in the attributte table (two features with the same name in different locations) and missing some districts compared to the list on https://www.iso.org/obp/ui/#iso:code:3166:LS

**Comment by lydiatroup** [comment]
@SidonieH this is one of the circumstances where we just have to go with what we have because the UN salb data isn't data we're meant to be editing the actual shapes of or anything. And one fix needs to be made for your LSO adm 1 file (make the ISO codes be the more specific ones not just LSO so the ls-d ones on the site you have linked above), otherwise everything is good.

**Comment by lydiatroup** [comment]
lfs uploaded them & closing this

**Pull request closed without merging**
