### PR TITLE
RUS_ADM0

### PR DESCRIPTION
**Pull request by alex-imb**
## Why do we need this boundary?  
In response to #3654 (RUS_ADM0 has significant amount of area in territorial waters)

## Anything Unusual?
Created by dissolving RUS_ADM1 from gbOpen

### CODE REVIEW

**Comment by alex-imb** [comment]
Hello, has anyone taken a look at this? Can I do anything to help?

**Comment by DanRunfola** [comment]
Apologies on the delay for this one - trying to find a block of time to carefully review, given the current geopolitical situation involving Russia.

**Comment by alex-imb** [comment]
Hi @DanRunfola, that makes sense. Thanks for the info.

**Comment by alex-imb** [comment]
Hello @DanRunfola and @Sarangaban. Why did this get closed? Does the zip need some additional information?

**Pull request closed without merging**
