### PR TITLE
AZE_ADM1 Issue #1742

### PR DESCRIPTION
**Pull request by dfornatora**
Correcting polygon names

## Why do we need this boundary?  
 /issues/1742

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Dominic- good work on this. Since we're offering a unique case with AZE_1 (autonomous republic vs contiguous region as opposed to the formalized rayon system of "adm1"), we should remove the ISO_Code field as there is no ISO 3166-2 distinction between the two. This will also lead to an issue in AZE_ADM2; we'll need to add 3166-2 codes to the 66 rayons. 
For now, in this file, let's remove the ISO_Code field and resubmit. I'll create a new issue for AZE2- this was an issue in the pre-existing file, your work was perfect! 
Thanks!

**Comment by lydiatroup** [comment]
@dfornatora just a reminder to this pr!

**Comment by dfornatora** [comment]
@lydiatroup changes were requested by @sgmurphy216 and then I submitted again. Are other changes needed?

**Comment by lydiatroup** [comment]
@sgmurphy216 please review this pr!!

**Review by sgmurphy216 — APPROVED** [review]

**Comment by sgmurphy216** [comment]
Looks good Dominic. Thanks!

**Comment by lydiatroup** [comment]
closes #1742

**Pull request merged**
