### PR TITLE
ZMB_ADM2 #1183

### PR DESCRIPTION
**Pull request by lydiatroup**
https://github.com/wmgeolab/geoBoundaries/issues/1183

### CODE REVIEW

**Review by sgmurphy216 — COMMENTED** [review]
Good job Lydia! Closes #1183

**Review by sgmurphy216 — APPROVED** [review]
Good job Lydia! Closes #1183

**Comment by DanRunfola** [comment]
Every time I see ZMB I think it's missing a piece...

**Comment by DanRunfola** [comment]
^^ Comment that starts an international incident.

**Pull request merged**
