### PR TITLE
NPL_ADM1

### PR DESCRIPTION
**Pull request by carolinamonrivera**
#118

## Why do we need this boundary?  
https://github.com/wmgeolab/gbRelease/issues/118

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Almost!! Change "DISTRICT" to "Name" in the attribute table :)

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Same feedback as ADM2: please update the license in meta and change the field names in the attribute table. It will initially fail because the correct license hasn't yet been added to the list, but don't worry about that.

**Comment by slfuhrig** [comment]
Will keep this PR open.

**Comment by slfuhrig** [comment]
Please make requested changes.

**Comment by sylviashea1** [comment]
@carolinamonrivera please make requested changes!

**Pull request closed without merging**
