### PR TITLE
DNK_ADM2 digitization Issue #1848

### PR DESCRIPTION
**Pull request by MichaelR-geoLab**

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
one quick change!
boundary representative of year should be 2007, since that's the year the image (that you digitized) is representative of
otherwise this looks amazing and is so incredibly detailed

**Comment by lydiatroup** [comment]
reopening for fall semester

**Comment by DanRunfola** [comment]
Pinging this - we'll be returning to this in the Fall and I don't want it to get marked stale.

**Comment by lydiatroup** [comment]
@MichaelR-geoLab pinging you on this - please change the date to 2007 and it will be good to go!

**Review by lydiatroup — APPROVED** [review]
perfect! thanks Michael - closes #1848

**Pull request merged**
