### PR TITLE
BDI_ADM1

### PR DESCRIPTION
**Pull request by taraamcl**
#2082

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Tara! Similar changes to before, the dd-mm-yyyy boundary representative field needs to be filled with hyphens, not slashes, and the UN SALB license should be listed as mentioned in the earlier PR. Thanks a bunch!

**Comment by lydiatroup** [comment]
@taraamcl reminder on this pr so we can close the bdi issue!

**Comment by lydiatroup** [comment]
@taraamcl two more small fixes! 
1) change source 1 in the meta to "From SALB Data, United Nations"
2) level field in the attribute table should be changed to ADM1
3) iso codes should be changed to the more specific ones for ADM1s (on this site https://www.iso.org/obp/ui/#iso:code:3166:BI)

**Comment by lydiatroup** [comment]
@taraamcl the shapefile itself looks good, only two changes for the meta:
1) **source 1** in the meta should be "From SALB Data, United Nations"
2) **license** in the meta should be "UN SALB Data License"
and then the bot should approve it and you'll be free of bdi

**Comment by taraamcl** [comment]
gotcha I'll get this done today!
________________________________

**Comment by lydiatroup** [comment]
closing bc new one was uploaded (and approved!)

**Pull request closed without merging**
