### PR TITLE
gbOpen IND_ADM5

### PR DESCRIPTION
**Pull request by leeberryman**

### CODE REVIEW

**Comment by sgmurphy216** [comment]
Hey Lee- just wanted to update you on where we are with this.

There appear to be some regions (primarily around reserves and rural areas) in which features are noncontiguous. With the granularity of this file, that makes sense. In other areas, like Andaman and Nicobar, there appears to be some distortion and a few missing elements in the features. Some more work is definitely in order on how to treat this, as a file of this size and granularity isn't easy to come by- will keep you up to date.

**Comment by leeberryman** [comment]
@sgmurphy216 do you have a list of the geometries that need to be addressed?  I have a complementary layer that fills gaps with forests and national parks, but it will not fill areas where villages have been placed with a point and buffer in areas that are disputed or restricted access like anuranchal pradesh and portions of jammu & kashmir, ladakh

**Comment by leeberryman** [comment]
@sgmurphy216 my team is taking a passing through cleaning up Andaman & Nicobar islands.   I'll merge the forest layer with these corrections and submit again.

**Comment by leeberryman** [comment]
closing to update new push

**Pull request closed without merging**
