### PR TITLE
#2015 AFG_ADM0

### PR DESCRIPTION
**Pull request by jingjli1**
Edits to the field name and visibility.

### CODE REVIEW

**Review by sgmurphy216 — COMMENTED** [review]
Looks good Jing! Going to triple check that 'open' is an acceptable license type, and will change this to an approval when we're sure it's all good. Thank you!

**Comment by lydiatroup** [comment]
@sgmurphy216

**Review by sgmurphy216 — APPROVED** [review]

**Comment by DanRunfola** [comment]
@sgmurphy216 same quesiton on this one - what issue #?

**Comment by sgmurphy216** [comment]
> @sgmurphy216 same quesiton on this one - what issue #?

#2015

**Pull request merged**
