### PR TITLE
#1755 ALB_ADM2

### PR DESCRIPTION
**Pull request by mlwilliams01**
## Why do we need this boundary?  
 #1755

### CODE REVIEW

**Comment by sgmurphy216** [comment]
Looks like this just failed because the license type isnt included in our bot list. It does look applicable though, so we'll get that added.

**Review by lydiatroup — CHANGES_REQUESTED** [review]
dan updated the license list to include this, so it should be working now if you reupload it with the license type as "Creative Commons Attribution 2.5 Generic"

**Comment by lydiatroup** [comment]
closing bc new pr was created

**Comment by DanRunfola** [comment]
@all-contributors add @mlwilliams01  to data

**Pull request closed without merging**
