### PR TITLE
#2016 AFG_ADM2

### PR DESCRIPTION
**Pull request by jingjli1**
Edits to field names and visibility.

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Jing! Same general feedback, we'll need to double check that 'open' is an acceptable license delineation. However, just a quick note, we only require the ISO_Code field in ADM0-1, so the field is not needed for this file. Once that's changed and we make sure on the license type, should be good to go! Thanks!

**Review by sgmurphy216 — APPROVED** [review]

**Comment by DanRunfola** [comment]
@sgmurphy216 I'm ready to accep this, but what issue number does it close?

**Comment by sgmurphy216** [comment]
> @sgmurphy216 I'm ready to accep this, but what issue number does it close?

#2016

**Comment by DanRunfola** [comment]
@jingjli1 thank you for the AFG contributions - hugely appreciated, and a geometry we've struggled to find.

**Pull request merged**
