### PR TITLE
#1014 gbOpen IND_ADM1

### PR DESCRIPTION
**Pull request by leeberryman**
#1014

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
Just one small change needed, otherwise this looks great! All we need is for you to change the license source field in your metadata to be the link to the webpage with the license information (the link to the page you screenshotted for your license.png file). Thank you!!

**Comment by leeberryman** [comment]
@lydiatroup done

**Comment by lydiatroup** [comment]
it looks like you changed the "Source 2" field, not the "License Source" one. Please fix the license source field to what you currently have in source 2!
Additionally, the ISO field in your geojson should be named ISO_Code.

**Comment by leeberryman** [comment]
@lydiatroup done

**Review by lydiatroup — APPROVED** [review]
This one looks good too! Thank you again for your submission and for working with us to get it submitted/uploaded correctly!

**Comment by DanRunfola** [comment]
Thank you for the contribution - we should see it get into the full build in the next day or so when the IND nightly runs.

**Pull request merged**
