### PR TITLE
IND_ADM2 #996

### PR DESCRIPTION
**Pull request by leeberryman**

### CODE REVIEW

**Comment by leeberryman** [comment]
corrected the meta.txt file to include exact match for Open Data Commons Open Database License 1.0

**Review by sgmurphy00 — CHANGES_REQUESTED** [review]
Hey Lee!

Submissions look great- thank you for the metadata correction. We would appreciate a screenshot of the source site, with url visible, to be included in the zip. Once we have that, everything looks good to go.

Thanks for your contributions,
Sean

**Review by lydiatroup — CHANGES_REQUESTED** [review]
Following up on this, all we need is a screenshot of the license to be able to add this to the database. Can you add one titled license.png?

**Review by lydiatroup — CHANGES_REQUESTED** [review]
For clarification on the license image, we're looking for a image that has the website in it and the page where it states what license the file has- aka where you found that the license is what you listed in the metadata.  

Also please remove the .0 in the year for the metadata and add the canonical boundary names (what the country refers to that level as- ex in usa adm1 is states)
Also in the metadata please add the link to the page that states the license type under "license source"

**Comment by lydiatroup** [comment]
This is going to be long, but I want to get all the corrections in one so we can get these files added!
The following corrections should help guide you for all the India files you're submitting

1) please complete the canonical name field in the metadata

2) please change the license source field in the metadata to be the link to the source info (the link to the page you screenshotted for the license)

3) please edit the fields in your geojson to be only the following: i) Name (which will contain the name of each feature), ii) Level (which will say ADMX, X being whatever adm level it is) iii) ISO code (which should only be present for ADM0 and ADM1)

4) For ease of submission, I ask you to submit one pull request for each adm level (1 for adm 0, 1 for adm1, etc) with the changes stated above, so we can review each one and hopefully approve them individually and get them added. With each file submitted to sourcedata -> gbOpen. I am going to close this pull request so you can create the others! Each file being uploaded should include the geojson, license.png, and meta.txt files.

Please let me know if you have any questions! You can just comment on this pull request page, and thank you for your contributions!

**Pull request closed without merging**
