### PR TITLE
BLZ_ADM0 gbOpen

### PR DESCRIPTION
**Pull request by geoBoundaryBot**
Boundary data for **BLZ-ADM0** submitted through the geoBoundaries contribution form. 
    

**Name**: Rohith.
**Affiliation**: Geolab.
**Contact**: rmandala@wm.edu.are files validated before they are uploaded to GitHub? Are there protections to ensure that the only expected file types/content can be uploaded?
**Notes about these data**:

### CODE REVIEW

**Review by Sarangaban — CHANGES_REQUESTED** [review]
Hi Rohith. We are not allowed to use open street map anymore so please find a different file. Additionally, make sure to merge the polygons since it's an ADM 0 and include a screenshot of the license. Thank you!

**Comment by DanRunfola** [comment]
@Sarangaban I asked Rohith to do this one even though it was OSM, in response to an issue in our issue tracker.  We still need to find a layer to replace OSM, but in the interim this will make it more accurate, so let's accept this as a temporary solution (after he's fixed the other issues).

**Comment by rohith4444** [comment]
Hi @Sarangaban, I have created new pull request #4146 where i have merged the polygons and attached license.png. Thank You!

**Comment by Sarangaban** [comment]
Closed. Resubmitted.

**Pull request closed without merging**
