### PR TITLE
#2070 gB Authoritative CYP 0-1

### PR DESCRIPTION
**Pull request by SidonieH**
## Why do we need this boundary?  
 #2070

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Sidonie! Please add canonical boundary name in meta if possible! Thank you!

**Comment by lydiatroup** [comment]
@SidonieH reminder to this pr!

**Comment by SidonieH** [comment]
It looks like it is uploaded? It says merging is blocked

**Comment by lydiatroup** [comment]
@SidonieH  the most recent update is still missing the canonical boundary name in the meta unless i’m missing a file

**Comment by SidonieH** [comment]
Just tried, let me know if it worked

**Comment by lydiatroup** [comment]
@sgmurphy216 approve this please

**Review by sgmurphy216 — APPROVED** [review]

**Pull request merged**
