### PR TITLE
#2019 AGO_ADM1

### PR DESCRIPTION
**Pull request by jingjli1**
Edited field names and proper casing.

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Jing! For the ADM1 files, we ask that the ISO_Code field is filled out with the ISO 3166-2 codes. For this, just go to the ISO country lookup website, to the 'Online Browsing Platform', search for your country, and scroll down a bit. There will be a list of each subdivision's code, one for each ADM1 unit. Thank you!

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
https://www.iso.org/obp/ui/#iso:code:3166:AO

**Comment by lydiatroup** [comment]
@sgmurphy216

**Review by sgmurphy216 — APPROVED** [review]
Great work Jing! Thanks so much! Closes #2019

**Pull request merged**
