### PR TITLE
BGD_ADM2 Issue #1383

### PR DESCRIPTION
**Pull request by dfornatora**
## Why do we need this boundary?  
 https://github.com/wmgeolab/geoBoundaries/issues/1383

### CODE REVIEW

**Comment by leeberryman** [comment]
@dfornatora This appears to be missing shapes for Kulna.  Is this a new source?

**Comment by dfornatora** [comment]
> @dfornatora This appears to be missing shapes for Kulna. Is this a new source?

Thank you for pointing this out. This was not a new source, this new commit was placing BGD_ADM2 into the correct subdirectory. I will look into this for the missing shapes.

**Comment by leeberryman** [comment]
@dfornatora 👍 I could help with it but I'm out for the next week.  If it's still pending I'll look.

**Comment by dfornatora** [comment]
> @dfornatora 👍 I could help with it but I'm out for the next week. If it's still pending I'll look.

Thank you! New source was found that includes all 64 districts

**Review by sgmurphy216 — APPROVED** [review]
Looks good @dfornatora - thanks for the correction, and thanks @leeberryman for pointing that out! Closes #1383

**Pull request merged**
