### PR TITLE
ABW_ADM0 gbOpen

### PR DESCRIPTION
**Pull request by geoBoundaryBot**
Boundary data for **ABW-ADM0** submitted through the geoBoundaries contribution form. 

**Name**: Jim Courson.
**Affiliation**: International Mission Board.
**Contact**: jcourson@imb.org.
**Notes about these data**: this is my first submission, but I hope to submit comparable shapes for a number of territories missing adm0 data

### CODE REVIEW

**Comment by DanRunfola** [comment]
Closing these out as we are updating the submission process for OCHA (going to write the API out better to accept gbHumanitarian, getting the checks to run correctly, etc.)

**Comment by leeberryman** [comment]
@DanRunfola these are not OCHA boundaries….

**Comment by DanRunfola** [comment]
Jim had said they were for the humanitarian dataset - my understanding was the issue at hand was we couldn't correctly classify these at time of upload.

If I am totally wrong we should do a quick video chat to clear up how to handle these. Shoot me an email (danr@wm.edu).

**Comment by DanRunfola** [comment]
Re-opening these; closed due to confusion with another set of requests.

To get these files working, they need to be:
A) Downloaded 
B) Opened in QGIS, and reprojected to EPSG 4326
C) Re-saved
D) The metadata needs to be updated to:
   D1) Change License Source to: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

Then, resubmit a new PR and *please remember to close this one*.

That should allow this to pass all the checks.

**Comment by lydiatroup** [comment]
submitted PR 2438 with the projection fixes to this pr

**Pull request closed without merging**
