### PR TITLE
FJI ADM3 gbOpen

### PR DESCRIPTION
**Pull request by kpupkiewicz**
## Why do we need this boundary?  

#1561

### CODE REVIEW

**Review by sgmurphy216 — DISMISSED** [review]
Looks great! Thank you! Closes #1580

**Comment by DanRunfola** [comment]
Oooo - this has a proper topological error we can't auto-correct.

Could you load this file into mapshaper.org and see if there is a quick/obvious way to fix the errors?

**Comment by kpupkiewicz** [comment]
I used the 'clean' function on mapshaper which appeared to fix the issue, but I think the bot failed it because when mapshaper exported the file, it changed around parts of the attribute table. Going to submit the same boundary with a fixed attribute table and hopefully it will work :E

**Review by sgmurphy216 — APPROVED** [review]
Looks great! Thanks! Closes #1561

**Pull request merged**
