### PR TITLE
gB OPEN CHN_ADM3 #1667

### PR DESCRIPTION
**Pull request by leeberryman**
corrected holes in ADM3

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Lee! This file looks great- thank you for your contribution! Could you include a .png of the OSM license page at https://www.openstreetmap.org/copyright and change 'source 1' in meta.txt to yourself? Since you worked directly with the geometries, you'll be attributed as source 1, and we'll need to add a wiki page documenting your changes (super short, only a few sentences required)

**Comment by leeberryman** [comment]
@sgmurphy216 I made the edits in the metadata and added the png.  I do see where the wiki pages are, but do not see where I can create one for CHN.

**Comment by leeberryman** [comment]
@sgmurphy216 I made the edits and found where to add a wiki page.  I made an entry for China.  Let me know if the wiki entry follows the pattern and need that you are trying to document.

**Review by sgmurphy216 — APPROVED** [review]
This looks great Lee! Thank you for your edits and wiki contribution. Closes #1667

**Pull request merged**
