### PR TITLE
NOR_ADM1 gbOpen

### PR DESCRIPTION
**Pull request by geoBoundaryBot**
Boundary data for **NOR-ADM1** submitted through the geoBoundaries contribution form. 

**Name**: Karim Bahgat.
**Affiliation**: William & Mary.
**Contact**: karim.bahgat.norway@gmail.com.
**Notes about these data**: Modifications: The original boundary was clipped to national land boundary using gbOpen ADM0.

### CODE REVIEW

**Comment by karimbahgat** [comment]
This is the first submission of an actual boundary contribution through the user contribution form (will soon be made available on the live website). 

As additional documentation, here is the Python 3 code used to load, reproject, and write the submitted shapefile. The input is the original geojson data file that was downloaded from the source url. 

```
import shapefile
from shapely.geometry import asShape
import pyproj
import json

# PARAMS
CLIP = True

# load geojson
layer = 'administrative_enheter.fylke'
with open('Basisdata_0000_Norge_25833_Fylker_GEOJSON.geojson', encoding='utf8') as f:
    geoj = json.loads(f.read())
print(geoj.keys())

# load reprojection
fromcrs = geoj[layer]['crs']['properties']['name']
tocrs = 'EPSG:4326'
transformer = pyproj.Transformer.from_crs(fromcrs, tocrs, always_xy=True)
def transform(coords):
    x,y = zip(*coords)
    newx,newy = transformer.transform(x, y)
    newcoords = list(zip(newx,newy))
    return newcoords
def transform_geom(geom):
    if geom['type'] in ('Polygon','MultiLineString'):
        geom['coordinates'] = [transform(ring) for ring in geom['coordinates']]
    elif geom['type'] == 'MultiPolygon':
        geom['coordinates'] = [[transform(ring) for ring in poly]
                                for poly in geom['coordinates']]
    elif geom['type'] == 'LineString':
        geom['coordinates'] = transform(geom['coordinates'])

# load national geoboundary to use for clipping
if CLIP:
    r = shapefile.Reader('https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/gbOpen/NOR/ADM0/geoBoundaries-NOR-ADM0.shp?raw=true')
    clip = asShape(r.shape(0).__geo_interface__)

# setup shapefile
w = shapefile.Writer('NOR_ADM1.shp')
fields = list(geoj[layer]['features'][0]['properties'].keys())
for field in fields:
    w.field(field, 'C')

# loop features and write to shapefile
for feat in geoj[layer]['features']:
    row = [feat['properties'].get(field,None) for field in fields]
    row[-1] = row[-1][0]['navn'] # last value is a list of dicts in original data
    print(row)
    w.record(*row)
    geom = feat['geometry']
    transform_geom(geom)
    if CLIP:
        shp = asShape(geom)
        clipped = shp.intersection(clip)
        geom = clipped.__geo_interface__
    w.shape(geom)
w.close()
```

**Comment by karimbahgat** [comment]
@DanRunfola who should i ping to get this reviewed? It's passed all tests and updates the data to the most recent adm1 changes around 2020 and is from an open government source.

**Comment by DanRunfola** [comment]
@lydiatroup @sgmurphy216

**Review by lydiatroup — CHANGES_REQUESTED** [review]
this iso codes in the attribute table all appear as "none." they should be the iso codes as found on this [site](https://www.iso.org/iso-3166-country-codes.html) -> open browsing platform, using the codes listed in the 3166-2 codes column

**Comment by karimbahgat** [comment]
@DanRunfola yes that would be good. I wanted to do it but then realized that since the data was submitted through the contribution tool, it's technically the geoBoundaryBot that owns the PR. This can be a good trial for how to proceed when users submit data through the contribution tool, where the contributor will not typically have github or be able to followup with edits or comments (the type of user we're targeting with the contribution tool). So maybe this could be a good trial for the team to figure out the best approach/procedures for making adjustments when the submitter cannot do it themselves. 

If it helps, here is the page with the codes: https://www.iso.org/obp/ui/#iso:code:3166:NO

**Comment by DanRunfola** [comment]
@lydiatroup @sgmurphy216 Anyone we can pull to do this update?

**Comment by lydiatroup** [comment]
@DanRunfola @sgmurphy216 Sidonie uploaded a new pr with the changes, but was unable to reupload to this pr (i tried too and wasnt able to either)

**Comment by DanRunfola** [comment]
@lydiatroup Aha!  Got it.  So closing this, as it's now migrated over to https://github.com/wmgeolab/geoBoundaries/pull/2234

**Pull request closed without merging**
