### PR TITLE
NRU_ADM1 #182

### PR DESCRIPTION
**Pull request by rsritchey**

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
This looks great! Thank you for digitizing- same thing as URY, please change the canonical boundary name field to the name of ADM1 in Nauru (county, province, region etc). Then we should be good to go! Thank you!

**Comment by rsritchey** [comment]
Corrected with ISO code

**Review by sgmurphy216 — APPROVED** [review]
Looks great! Thank you! Closes #182

**Comment by DanRunfola** [comment]
Look ma, no giant hole in the middle of the island!

**Pull request merged**
