### PR TITLE
GMB_ADM1 gbOpen

### PR DESCRIPTION
**Pull request by kpupkiewicz**
## Why do we need this boundary?  

#2291 

## Anything Unusual?

shapeISO's have yet to be updated by ISO to accommodate the new administrative structure. Current submission uses the previous structure, and some LGA's (local government areas) will share shapeISO labels that applied to their previous divisions.

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
A few necessary changes and this file will be good to go
1) change the license in the metadata to "Creative Commons Attribution 4.0 (CC BY 4.0)" and remove that from the license notes
2) Canonical boundary name appears to be region not local government areas

**Comment by kpupkiewicz** [comment]
Good catch @lydiatroup !
I did get an email when I uploaded the new file, https://github.com/wmgeolab/geoBoundaries/actions/runs/3048104091 - I don't know enough about github to say whether or not this is important but I figured I'd make sure you saw it nonetheless.

**Review by lydiatroup — APPROVED** [review]
Thanks for the fix! closes #2291

**Comment by lydiatroup** [comment]
@kpupkiewicz I get emails from each PR run so I did see that, but the file looks all good now so I went ahead and approved it!

**Pull request merged**
