### PR TITLE
LVA_ADM2 #1659

### PR DESCRIPTION
**Pull request by ejott**

### CODE REVIEW

**Comment by lydiatroup** [comment]
will also address 1694

**Review by lydiatroup — CHANGES_REQUESTED** [review]
only one fix needed: if the file was NOT digitized please remove geoboundaries from source 1. otherwise, disregard this

**Comment by ejott** [comment]
> only one fix needed: if the file was NOT digitized please remove geoboundaries from source 1. otherwise, disregard this

Gotcha, I did have to change it (and LVA_ADM0) from .gml to .shp which is why I included that b/c that was a bit of a process for me but thinking back that's not really digitization, is it? will fix and remove

**Comment by lydiatroup** [comment]
> > only one fix needed: if the file was NOT digitized please remove geoboundaries from source 1. otherwise, disregard this
> 
> Gotcha, I did have to change it (and LVA_ADM0) from .gml to .shp which is why I included that b/c that was a bit of a process for me but thinking back that's not really digitization, is it? will fix and remove

A little more info on this for you. The reason we put geoboundaries as source one for digitization is because we are then CREATING the file itself. In cases like yours or when dissolving a boundary, making a few minor edits, you are editing the existing as opposed to creating it from scratch, so geoBoundaries isn't a source. In essence, this 'source' is asking for where geoBoundaries found the file!

**Pull request closed without merging**
