### PR TITLE
CHL_ADM0 gbAuthoritative

### PR DESCRIPTION
**Pull request by nmspage**
## Why do we need this boundary?  
 #696

### CODE REVIEW

**Comment by nmspage** [comment]
This is @taraamcl 's PR

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Natalie/Tara! Few changes to be made here: please resubmit a .zip with all supporting files (missing .prj; just re-export the data from arc or q and re-zip, should be fine). Also, in meta.txt, you put 'gb open' as release type, this should be authoritative. Finally, just check your projection and we should be good to go! Thanks!

**Review by sgmurphy216 — APPROVED** [review]
Looks great! Thanks! Closes #696

**Comment by DanRunfola** [comment]
Thank you!

**Pull request merged**
