### PR TITLE
NPL_ADM2

### PR DESCRIPTION
**Pull request by carolinamonrivera**
#119

## Why do we need this boundary?  
https://github.com/wmgeolab/gbRelease/issues/119

## Checklist:

- [X ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [X ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
So close! We just need a couple changes in the shapefile itself:

1. We need a "Name" field instead of the Districts one we have right now.
2. Remove ISO_Code since this is ADM 2

**Review by slfuhrig — CHANGES_REQUESTED** [review]
So close!!! Please change the name of the "DISTRICTS" field to be "Name". Let me know if you have any questions :)

**Review by slfuhrig — CHANGES_REQUESTED** [review]
So close!! Please change the license in meta to match what's in the jpeg (will be approved once added to the list), then change the names of the attribute table fields to match what we want (DISTRICT > Name, others to not be in all caps).

**Comment by slfuhrig** [comment]
Will keep this PR open.

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Please name a "Name" field instead of the current "Districts" one you've got in the attribute table.

**Comment by sylviashea1** [comment]
@carolinamonrivera please make requested changes!

**Review by slfuhrig — APPROVED** [review]

**Comment by DanRunfola** [comment]
I am confused :).  We already accepted this in on Feb 12:
https://github.com/wmgeolab/geoBoundaries/commit/c70a1d097e9c5107510f2dc926219793297403d9

Is this different?

**Comment by slfuhrig** [comment]
It appears that this is somehow a duplicate PR, so will close.

**Pull request closed without merging**
