### PR TITLE
#2046 GHA_ADM2

### PR DESCRIPTION
**Pull request by jingjli1**
ADM2 names changed to proper case.

### CODE REVIEW

**Comment by sgmurphy216** [comment]
Hey Jing! Looks like you're missing a meta.txt in your zip file. You can download a zipped file from any successful PR (green check in pull requests tab) and use the meta.txt as a template to fill out your metadata. Thank you!

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
See comment.

**Comment by jingjli1** [comment]
Thank you Sean!

**Comment by lydiatroup** [comment]
@sgmurphy216 this was marked as stale please review this issue asap

**Review by sgmurphy216 — APPROVED** [review]
Looks good Jing- sorry I missed this! Closes #2046

**Comment by DanRunfola** [comment]
@all-contributors add @jingjli1  to data

**Pull request merged**
