### PR TITLE
GBR_ADM1 #2558

### PR DESCRIPTION
**Pull request by amanda-reed**
## Why do we need this boundary?  
 #2558 

Submitted on behalf of @hadleyday

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
license should be "Creative Commons Attribution 4.0 International (CC BY 4.0)"

also please remove the "any other relevant info if applicable" from the other notes section in the meta file

**Comment by lydiatroup** [comment]
@hadleyday

**Comment by lydiatroup** [comment]
@amanda-reed  hey amanda, can you try reupload this?

**Comment by amanda-reed** [comment]
I was having trouble committing changes from this branch so I created a new PR and reuploaded the file. I'll close this PR when #2839 is good to go

**Pull request closed without merging**
