### PR TITLE
gB OPEN MYS ADM3 Issue #2108

### PR DESCRIPTION
**Pull request by MichaelR-geoLab**
found a shapefile for MYA_ADM3 and cleaned it up.

### CODE REVIEW

**Review by sgmurphy216 — CHANGES_REQUESTED** [review]
Hey Michael- couple oddities with this one. First off, please reproject to EPSG: 4326 you were in Mercator '84 through CRS84 . This *should* clear up the geometry issues. Looks like our bot doesn't include MYA, so I'll have a talk with the bot overlord about it. Thanks a bunch.

**Comment by lydiatroup** [comment]
@MichaelR-geoLab looks like the ISO code on this should be MMR (for myanmar)! please change this in addition to the projection!

**Comment by lydiatroup** [comment]
@MichaelR-geoLab reminder about this pr! all it needs is to be reprojected

**Comment by lydiatroup** [comment]
new pr made for this, closing this one

**Pull request closed without merging**
