### PR TITLE
#1141 gbOpen IND_ADM2

### PR DESCRIPTION
**Pull request by leeberryman**

### CODE REVIEW

**Comment by slfuhrig** [comment]
Hi @leeberryman thank you so much!! Your checks are failing because you have uploaded files to both the root in addition to our source data folder. To fix the problem (and pass our checks so we can accept the files), please delete the two files that are currently uploaded to the root while keeping the files with the extension sourceData/gbOpen/IND_ADM2.zip etc.

Again, thank you so much and please let us know if you have any questions or problems.

**Comment by leeberryman** [comment]
@slfuhrig I removed the files in root folder.

**Comment by leeberryman** [comment]
I made new pull requests seperating each issue and each commit.

**Comment by DanRunfola** [comment]
@all-contributors add @leeberryman  to data

**Pull request closed without merging**
