### PR TITLE
Issue #1171 TWN_ADM1

### PR DESCRIPTION
**Pull request by hadleyday**

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
A couple changes are needed and then it'll be good!
1) your attribute table has an empty "Level" field, and a "Level_1" field with the level in it. (only need 1 "Level" with the level)
2) the meta issue with dan lol

**Review by lydiatroup — CHANGES_REQUESTED** [review]
your zip file has the folder with all the stuff titled "TWN_ADM1" and a "mac os" file so it's failing the meta checks since the bot can't access the metadata (bc it's in a subfolder). 
also your shapefile has 2 fields for level, 'level' which is empty and 'level_1' which has the adm # please fix these issues and resubmit!

**Review by lydiatroup — CHANGES_REQUESTED** [review]
still a couple issues left:
1) there's an empty folder called 'new folder' in your zipfile, please remove this
2) there's still two columns for level (level which is null and level_1 which has the correct values)
please fix these and resubmit!

**Review by lydiatroup — APPROVED** [review]
looks great! thanks hadley! Closes issue #1171

**Comment by DanRunfola** [comment]
Glad to see this one made it through :)  Thank you!

**Pull request merged**
