### PR TITLE
#1015 gbOpen IND_ADM0

### PR DESCRIPTION
**Pull request by leeberryman**
#1015

### CODE REVIEW

**Review by lydiatroup — CHANGES_REQUESTED** [review]
Only one small change is needed, otherwise this looks great! Please change the license source in the metadata to the link of the site that shows the license information (the site you screenshotted for the license png). Thank you!

**Comment by leeberryman** [comment]
@lydiatroup done

**Comment by lydiatroup** [comment]
@leeberryman it looks like you changed the "Source 2" field, not the "License Source" one. Please fix the license source field to what you currently have in source 2!
Additionally, the ISO field in your geojson should be named ISO_Code.

**Comment by leeberryman** [comment]
@lydiatroup done

**Review by lydiatroup — APPROVED** [review]
This looks perfect! Thank you for submitting this file and working with us to get submitted properly!

**Comment by DanRunfola** [comment]
Thank you for the submission - should get pulled into the built data during the next nightly.

**Pull request merged**
