### PR TITLE
ESP_ADM4 gbOpen

### PR DESCRIPTION
**Pull request by nmspage**
## Anything Unusual?
 This is @MichaelR-geoLab 's work, issue number #137

### CODE REVIEW

**Review by sgmurphy216 — APPROVED** [review]
Manual inspection looks good! Thanks @MichaelR-geoLab and @nmspage ! Closes #137

**Comment by DanRunfola** [comment]
mmm, there are so many ADM units that the bot seems to be crashing.  Going to work on this one before I accept it.

**Comment by DanRunfola** [comment]
OK! 

image

Looks like there is at least one feature that is missing a geometry - i.e., it's a record only in the attribute table.  So, we need to find that before we can accept this boundary.

@nmspage @sgmurphy216

**Comment by sgmurphy216** [comment]
Err- does not exist, municipal level = adm3

**Pull request closed without merging**
